### ISSUE TITLE
Politie missing

### ISSUE THREAD

**Issue by poudenes** [cyberjunky/home-assistant-p2000#17]
Hi All,

I get all the info correct, but politie is missing all the time

Kind Regards,
Peter

**Comment by cyberjunky** [comment]
In my region there is hardly any Police data available because they use other systems (their communication is more private)

Which region are you in, what do you see when you query the site with your regio (r= for only police data (d=3)

https://feeds.livep2000.nl/?r=18&d=3

This data should be available in p2000 hass integration when you specify disciplines: 1,2,3,4

**Comment by poudenes** [comment]
What I have done now. (don't know why I did figure out earlier) Made a sensor for R=13&D=3
So Amsterdam Amstelland and only Police.

Then I have a sensor just for Amsterdam Amstelland Politie.

Lets see if I get some info

**Comment by poudenes** [comment]
I get Police information. There is so many things happen in Amsterdam so I didn't see them.
There was nothing wrong at the end.. :)
