### ISSUE TITLE
Request: support for zones

### ISSUE THREAD

**Issue by metbril** [cyberjunky/home-assistant-p2000#2]
Instead of specifying lat/lon with radius use a zone from Home Assistant.

    sensor:
      - platform: p2000
        regios: 18
        disciplines: 1,2,3,4
        radius: 5000
        zone: work

uses the 'zone.work' entity.

**Comment by cyberjunky** [comment]
Nice idea. Do you mean drop the lat/long option and implement this instead or make one of them required?

**Comment by metbril** [comment]
As far as I"m concerned this should be the order:

1. Lat/Lon when explicitly defined
2. Zone when defined
3. Default to home location from config

If both lat/Lon are specified you could follow this order but you can also raise an error if both zone AND lat/Lon are specified.

**Comment by elektrikal80** [comment]
Question, why did the p2000 sensor nothing ?? 

 - platform: p2000
    regios: 18
    disciplines: 1,2,3
    scan_interval: 20
    capcodes: 0803125,0803126,0803127,0803128,0803129,0803130,0803132,0803136,0803137,0803138,0803139,0803150,0803151,0803152,0803153,0803123,0803002,0806476,0806477,0806479,0120901,0923993,1420059,0820157,0820159

  - platform: p2000
    name: woonplaats
    regios: 6
    disciplines: 1,2,3
    radius: 10000
    scan_interval: 10
    latitude: 51.9725
    longitude: 6.71944

can you help me??

**Comment by aavosnl** [comment]
Forget the first zero @ all capcodes starting with zero aka 0803125   type > 803125 en start directley after capcodes: with the first capcodeVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: elektrikal80 <notifications@github.com> Datum: 18-03-2020  19:50  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 <home-assistant-p2000@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: Re: [cyberjunky/home-assistant-p2000] Request: support for zones (#2) 
Question, why did the p2000 sensor nothing ??


platform: p2000
regios: 18
disciplines: 1,2,3
scan_interval: 20
capcodes: 0803125,0803126,0803127,0803128,0803129,0803130,0803132,0803136,0803137,0803138,0803139,0803150,0803151,0803152,0803153,0803123,0803002,0806476,0806477,0806479,0120901,0923993,1420059,0820157,0820159


platform: p2000
name: woonplaats
regios: 6
disciplines: 1,2,3
radius: 10000
scan_interval: 10
latitude: 51.9725
longitude: 6.71944


can you help me??

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cyberjunky/home-assistant-p2000/issues/2#issuecomment-600801887",
"url": "https://github.com/cyberjunky/home-assistant-p2000/issues/2#issuecomment-600801887",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by aavosnl** [comment]
And dont forget to fil the codes voor regios Regios: 6,7,8,18  and al.the codes where the capcodes fromVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: elektrikal80 <notifications@github.com> Datum: 18-03-2020  19:50  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 <home-assistant-p2000@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: Re: [cyberjunky/home-assistant-p2000] Request: support for zones (#2) 
Question, why did the p2000 sensor nothing ??


platform: p2000
regios: 18
disciplines: 1,2,3
scan_interval: 20
capcodes: 0803125,0803126,0803127,0803128,0803129,0803130,0803132,0803136,0803137,0803138,0803139,0803150,0803151,0803152,0803153,0803123,0803002,0806476,0806477,0806479,0120901,0923993,1420059,0820157,0820159


platform: p2000
name: woonplaats
regios: 6
disciplines: 1,2,3
radius: 10000
scan_interval: 10
latitude: 51.9725
longitude: 6.71944


can you help me??

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cyberjunky/home-assistant-p2000/issues/2#issuecomment-600801887",
"url": "https://github.com/cyberjunky/home-assistant-p2000/issues/2#issuecomment-600801887",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by elektrikal80** [comment]
Thx, i removed the 0 bevore the caps code, but the caps code are from regio 6, Noord en oost gelderland, why must i fil in other codes bij regios: , is 6 not good??

**Comment by aavosnl** [comment]
Yes that is ok,  but in your list there is also a capcode starting with 14.Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: elektrikal80 <notifications@github.com> Datum: 18-03-2020  20:29  (GMT+01:00) Aan: cyberjunky/home-assistant-p2000 <home-assistant-p2000@noreply.github.com> Cc: berthwk <bert@vpharderwijk.nl>, Comment <comment@noreply.github.com> Onderwerp: Re: [cyberjunky/home-assistant-p2000] Request: support for zones (#2) 
Thx, i removed the 0 bevore the caps code, but the caps code are from regio 6, Noord en oost gelderland, why must i fil in other codes bij regios: , is 6 not good??

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cyberjunky/home-assistant-p2000/issues/2#issuecomment-600818062",
"url": "https://github.com/cyberjunky/home-assistant-p2000/issues/2#issuecomment-600818062",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by elektrikal80** [comment]
sorry youre right , thank you

**Comment by cyberjunky** [comment]
I have updated the documentation.
